using System.Diagnostics.CodeAnalysis;
#pragma warning disable CS1591
#pragma warning disable SA1600

namespace MonorailCss.Css;

/// <summary>
/// Collection of stand CSS property names.
/// </summary>
[SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private")]
public static class CssProperties
{
    // future me will convert these to constants.
    public static string Appearance = nameof(Appearance).ToKebabCase();
    public static string Animation = nameof(Animation).ToKebabCase();
    public static string Background = nameof(Background).ToKebabCase();
    public static string BackgroundAttachment = nameof(BackgroundAttachment).ToKebabCase();
    public static string BackgroundClip = nameof(BackgroundClip).ToKebabCase();
    public static string BackgroundColor = nameof(BackgroundColor).ToKebabCase();
    public static string BackgroundImage = nameof(BackgroundImage).ToKebabCase();
    public static string BackgroundOrigin = nameof(BackgroundOrigin).ToKebabCase();
    public static string BackgroundPosition = nameof(BackgroundPosition).ToKebabCase();
    public static string BackgroundRepeat = nameof(BackgroundRepeat).ToKebabCase();
    public static string BackgroundSize = nameof(BackgroundSize).ToKebabCase();
    public static string Border = nameof(Border).ToKebabCase();
    public static string BorderBottom = nameof(BorderBottom).ToKebabCase();
    public static string BorderBottomColor = nameof(BorderBottomColor).ToKebabCase();
    public static string BorderBottomLeftRadius = nameof(BorderBottomLeftRadius).ToKebabCase();
    public static string BorderBottomRightRadius = nameof(BorderBottomRightRadius).ToKebabCase();
    public static string BorderBottomStyle = nameof(BorderBottomStyle).ToKebabCase();
    public static string BorderBottomWidth = nameof(BorderBottomWidth).ToKebabCase();
    public static string BorderCollapse = nameof(BorderCollapse).ToKebabCase();
    public static string BorderColor = nameof(BorderColor).ToKebabCase();
    public static string BorderImage = nameof(BorderImage).ToKebabCase();
    public static string BorderImageOutset = nameof(BorderImageOutset).ToKebabCase();
    public static string BorderImageRepeat = nameof(BorderImageRepeat).ToKebabCase();
    public static string BorderImageSlice = nameof(BorderImageSlice).ToKebabCase();
    public static string BorderImageSource = nameof(BorderImageSource).ToKebabCase();
    public static string BorderImageWidth = nameof(BorderImageWidth).ToKebabCase();
    public static string BorderLeft = nameof(BorderLeft).ToKebabCase();
    public static string BorderLeftColor = nameof(BorderLeftColor).ToKebabCase();
    public static string BorderLeftStyle = nameof(BorderLeftStyle).ToKebabCase();
    public static string BorderLeftWidth = nameof(BorderLeftWidth).ToKebabCase();
    public static string BorderRadius = nameof(BorderRadius).ToKebabCase();
    public static string BorderRight = nameof(BorderRight).ToKebabCase();
    public static string BorderRightColor = nameof(BorderRightColor).ToKebabCase();
    public static string BorderRightStyle = nameof(BorderRightStyle).ToKebabCase();
    public static string BorderRightWidth = nameof(BorderRightWidth).ToKebabCase();
    public static string BorderSpacing = nameof(BorderSpacing).ToKebabCase();
    public static string BorderStyle = nameof(BorderStyle).ToKebabCase();
    public static string BorderTop = nameof(BorderTop).ToKebabCase();
    public static string BorderTopColor = nameof(BorderTopColor).ToKebabCase();
    public static string BorderTopLeftRadius = nameof(BorderTopLeftRadius).ToKebabCase();
    public static string BorderTopRightRadius = nameof(BorderTopRightRadius).ToKebabCase();
    public static string BorderTopStyle = nameof(BorderTopStyle).ToKebabCase();
    public static string BorderTopWidth = nameof(BorderTopWidth).ToKebabCase();
    public static string BorderWidth = nameof(BorderWidth).ToKebabCase();
    public static string Bottom = nameof(Bottom).ToKebabCase();
    public static string BoxShadow = nameof(BoxShadow).ToKebabCase();
    public static string CaptionSide = nameof(CaptionSide).ToKebabCase();
    public static string Clear = nameof(Clear).ToKebabCase();
    public static string Clip = nameof(Clip).ToKebabCase();
    public static string Color = nameof(Color).ToKebabCase();
    public static string Content = nameof(Content).ToKebabCase();
    public static string CounterIncrement = nameof(CounterIncrement).ToKebabCase();
    public static string CounterReset = nameof(CounterReset).ToKebabCase();
    public static string Cursor = nameof(Cursor).ToKebabCase();
    public static string Direction = nameof(Direction).ToKebabCase();
    public static string Display = nameof(Display).ToKebabCase();
    public static string EmptyCells = nameof(EmptyCells).ToKebabCase();
    public static string Float = nameof(Float).ToKebabCase();
    public static string Font = nameof(Font).ToKebabCase();
    public static string FontFamily = nameof(FontFamily).ToKebabCase();
    public static string FontSize = nameof(FontSize).ToKebabCase();
    public static string FontSizeAdjust = nameof(FontSizeAdjust).ToKebabCase();
    public static string FontStretch = nameof(FontStretch).ToKebabCase();
    public static string FontStyle = nameof(FontStyle).ToKebabCase();
    public static string FontSynthesis = nameof(FontSynthesis).ToKebabCase();
    public static string FontVariant = nameof(FontVariant).ToKebabCase();
    public static string FontWeight = nameof(FontWeight).ToKebabCase();
    public static string Height = nameof(Height).ToKebabCase();
    public static string Left = nameof(Left).ToKebabCase();
    public static string LetterSpacing = nameof(LetterSpacing).ToKebabCase();
    public static string LineHeight = nameof(LineHeight).ToKebabCase();
    public static string ListStyle = nameof(ListStyle).ToKebabCase();
    public static string ListStyleImage = nameof(ListStyleImage).ToKebabCase();
    public static string ListStylePosition = nameof(ListStylePosition).ToKebabCase();
    public static string ListStyleType = nameof(ListStyleType).ToKebabCase();
    public static string Margin = nameof(Margin).ToKebabCase();
    public static string MarginBottom = nameof(MarginBottom).ToKebabCase();
    public static string MarginLeft = nameof(MarginLeft).ToKebabCase();
    public static string MarginRight = nameof(MarginRight).ToKebabCase();
    public static string MarginTop = nameof(MarginTop).ToKebabCase();
    public static string MaxHeight = nameof(MaxHeight).ToKebabCase();
    public static string MaxWidth = nameof(MaxWidth).ToKebabCase();
    public static string MinHeight = nameof(MinHeight).ToKebabCase();
    public static string MinWidth = nameof(MinWidth).ToKebabCase();
    public static string Opacity = nameof(Opacity).ToKebabCase();
    public static string Orphans = nameof(Orphans).ToKebabCase();
    public static string Outline = nameof(Outline).ToKebabCase();
    public static string OutlineColor = nameof(OutlineColor).ToKebabCase();
    public static string OutlineOffset = nameof(OutlineOffset).ToKebabCase();
    public static string OutlineStyle = nameof(OutlineStyle).ToKebabCase();
    public static string OutlineWidth = nameof(OutlineWidth).ToKebabCase();
    public static string Overflow = nameof(Overflow).ToKebabCase();
    public static string Padding = nameof(Padding).ToKebabCase();
    public static string PaddingBottom = nameof(PaddingBottom).ToKebabCase();
    public static string PaddingLeft = nameof(PaddingLeft).ToKebabCase();
    public static string PaddingRight = nameof(PaddingRight).ToKebabCase();
    public static string PaddingTop = nameof(PaddingTop).ToKebabCase();
    public static string PageBreakAfter = nameof(PageBreakAfter).ToKebabCase();
    public static string PageBreakBefore = nameof(PageBreakBefore).ToKebabCase();
    public static string PageBreakInside = nameof(PageBreakInside).ToKebabCase();
    public static string PointerEvents = nameof(PointerEvents).ToKebabCase();
    public static string Position = nameof(Position).ToKebabCase();
    public static string Quotes = nameof(Quotes).ToKebabCase();
    public static string Right = nameof(Right).ToKebabCase();
    public static string TableLayout = nameof(TableLayout).ToKebabCase();
    public static string TextAlign = nameof(TextAlign).ToKebabCase();
    public static string TextDecoration = nameof(TextDecoration).ToKebabCase();
    public static string TextIndent = nameof(TextIndent).ToKebabCase();
    public static string TextTransform = nameof(TextTransform).ToKebabCase();
    public static string Top = nameof(Top).ToKebabCase();
    public static string Transform = nameof(Transform).ToKebabCase();
    public static string TransformOrigin = nameof(TransformOrigin).ToKebabCase();
    public static string Transition = nameof(Transition).ToKebabCase();
    public static string TransitionDelay = nameof(TransitionDelay).ToKebabCase();
    public static string TransitionDuration = nameof(TransitionDuration).ToKebabCase();
    public static string TransitionProperty = nameof(TransitionProperty).ToKebabCase();
    public static string TransitionTimingFunctionUnicodeBidi = nameof(TransitionTimingFunctionUnicodeBidi).ToKebabCase();
    public static string VerticalAlign = nameof(VerticalAlign).ToKebabCase();
    public static string Visibility = nameof(Visibility).ToKebabCase();
    public static string WhiteSpace = nameof(WhiteSpace).ToKebabCase();
    public static string Widows = nameof(Widows).ToKebabCase();
    public static string Width = nameof(Width).ToKebabCase();
    public static string WordSpacing = nameof(WordSpacing).ToKebabCase();
    public static string ZIndex = nameof(ZIndex).ToKebabCase();
}